### ISSUE TITLE
Multiple releases from matrix strategy

### ISSUE THREAD

**Issue by heitzmann** [anton-yurchenko/git-release#36]
### Description:  
When running a matrix strategy, each providing one release file, the action ends up creating one (draft) release for each matrix run, all with the same name. It seems it would make more sense to create a single release with all build products.

### Reference:
[Here](https://github.com/heitzmann/gdstk/blob/0e52f250f7d87beaaafe659014a2b466d391e147/.github/workflows/docs.yml) is the workflow I'm using, for reference.

This workflow creates 3 draft releases, all named "Release XXX", each with one installation file for Windows for Python versions 3.6, 3.7 and 3.8.

Is there any configuration I'm missing that would create a single release with all 3 files?

(Thanks for the great action, btw!)

**Comment by anton-yurchenko** [comment]
Hey @heitzmann,
Each time you call **git-release** it will try to create a GitHub release.

I believe you should have a dedicated **job** that will wait for all the others to finish and only then create the release.
You will have to stash/unstash build artifacts in order to move them between jobs.

Something like: 
![image](https://user-images.githubusercontent.com/33016810/95009571-c09ff180-062b-11eb-896b-d2e80bdb429c.png)

**Comment by heitzmann** [comment]
Got it, I'll try to refactor the workflow to make it work as you describe. Thanks!
